spring:
  application:
    name: protag
  datasource:
    mysql-jpa:
      jdbc-url: jdbc:h2:mem:testdb1;MODE=MySQL
      username: sa
      password:
      driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
